language: python
python:
  - "2.7"
  - "3.4"
  - "nightly"

install: "pip install -r requirements-test.txt"
script: "python -m unittest discover"

notifications:
  email:
    recipients:
      - laguta@ispras.ru
    on_failure: change
    on_success: never

